<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DataLayer\Nachos.DataLayer.SqlServer\Nachos.DataLayer.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Fixtures\*.xml;Fixtures\*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>