<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nachos.Core\Nachos.Core.csproj" />
    <ProjectReference Include="..\Nachos.Abstractions\Nachos.Abstractions.csproj" />
    <ProjectReference Include="..\DataLayer\Nachos.DataLayer.SqlServer\Nachos.DataLayer.SqlServer.csproj" />
  </ItemGroup>
</Project>
