<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nachos.Abstractions\Nachos.Abstractions.csproj" />
  </ItemGroup>
</Project>
