/*
Deployment script for nachos_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "nachos_db"
:setvar DefaultFilePrefix "nachos_db"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY CHECKSUM 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 60 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
PRINT N'Creating Table [dbo].[IdempotencyRecords]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[IdempotencyRecords] (
    [Id]             BIGINT             IDENTITY (1, 1) NOT NULL,
    [WorkspaceId]    BIGINT             NOT NULL,
    [KeyHash]        BINARY (32)        NOT NULL,
    [Key]            NVARCHAR (255)     COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL,
    [RequestHash]    CHAR (64)          NOT NULL,
    [ResponseStatus] INT                NOT NULL,
    [ResponseBody]   NVARCHAR (MAX)     NOT NULL,
    [ExpiresAt]      DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_IdempotencyRecords] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_IdempotencyRecords_Workspace_KeyHash] UNIQUE NONCLUSTERED ([WorkspaceId] ASC, [KeyHash] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Index [dbo].[IdempotencyRecords].[IX_IdempotencyRecords_ExpiresAt]...';


GO
CREATE NONCLUSTERED INDEX [IX_IdempotencyRecords_ExpiresAt]
    ON [dbo].[IdempotencyRecords]([ExpiresAt] ASC);


GO
PRINT N'Creating Foreign Key [dbo].[FK_IdempotencyRecords_Workspaces]...';


GO
ALTER TABLE [dbo].[IdempotencyRecords] WITH NOCHECK
    ADD CONSTRAINT [FK_IdempotencyRecords_Workspaces] FOREIGN KEY ([WorkspaceId]) REFERENCES [dbo].[Workspaces] ([Id]);


GO
/*
Post-deployment script: stamps the single SchemaVersion row.
Idempotent: safe to run on every deploy. Monotonic: the stamp only ever moves forward, so running an older
script against a newer database cannot make it look older (SchemaDeployer refuses to deploy over one anyway).

The version literal below must equal SchemaInfo.CurrentVersion in
Nachos.DataLayer.SqlServer (asserted by SchemaDeployerTests.PostDeployVersion_MatchesSchemaInfo).
*/
MERGE [dbo].[SchemaVersion] AS target
USING (SELECT CAST(1 AS TINYINT) AS [Id], 1 AS [Version]) AS source -- SCHEMA VERSION LITERAL: keep in sync with SchemaInfo.CurrentVersion
ON target.[Id] = source.[Id]
WHEN MATCHED AND target.[Version] < source.[Version] THEN
    UPDATE SET [Version] = source.[Version], [AppliedAt] = SYSUTCDATETIME()
WHEN NOT MATCHED THEN
    INSERT ([Id], [Version], [AppliedAt]) VALUES (source.[Id], source.[Version], SYSUTCDATETIME());
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[IdempotencyRecords] WITH CHECK CHECK CONSTRAINT [FK_IdempotencyRecords_Workspaces];


GO
PRINT N'Update complete.';


GO
