/*
Deployment script for nachos_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "nachos_db"
:setvar DefaultFilePrefix "nachos_db"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE,
                DISABLE_BROKER 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Creating Table [dbo].[IdempotencyRecords]...';


GO
CREATE TABLE [dbo].[IdempotencyRecords] (
    [Id]             BIGINT             IDENTITY (1, 1) NOT NULL,
    [WorkspaceId]    BIGINT             NOT NULL,
    [KeyHash]        BINARY (32)        NOT NULL,
    [Key]            NVARCHAR (255)     COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL,
    [RequestHash]    CHAR (64)          NOT NULL,
    [ResponseStatus] INT                NOT NULL,
    [ResponseBody]   NVARCHAR (MAX)     NOT NULL,
    [ExpiresAt]      DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_IdempotencyRecords] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_IdempotencyRecords_Workspace_KeyHash] UNIQUE NONCLUSTERED ([WorkspaceId] ASC, [KeyHash] ASC)
);


GO
PRINT N'Creating Index [dbo].[IdempotencyRecords].[IX_IdempotencyRecords_ExpiresAt]...';


GO
CREATE NONCLUSTERED INDEX [IX_IdempotencyRecords_ExpiresAt]
    ON [dbo].[IdempotencyRecords]([ExpiresAt] ASC);


GO
PRINT N'Creating Table [dbo].[Messages]...';


GO
CREATE TABLE [dbo].[Messages] (
    [Id]               BIGINT             IDENTITY (1, 1) NOT NULL,
    [WorkspaceId]      BIGINT             NOT NULL,
    [SessionId]        BIGINT             NOT NULL,
    [PeerId]           BIGINT             NOT NULL,
    [PublicId]         NVARCHAR (32)      COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL,
    [Seq]              BIGINT             NOT NULL,
    [Content]          NVARCHAR (MAX)     NOT NULL,
    [TokenCount]       INT                NOT NULL,
    [Metadata]         JSON               NOT NULL,
    [InternalMetadata] JSON               NOT NULL,
    [CreatedAt]        DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_Messages] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_Messages_PublicId] UNIQUE NONCLUSTERED ([PublicId] ASC),
    CONSTRAINT [UQ_Messages_Session_Seq] UNIQUE NONCLUSTERED ([SessionId] ASC, [Seq] ASC)
);


GO
PRINT N'Creating Index [dbo].[Messages].[IX_Messages_Workspace_Peer]...';


GO
CREATE NONCLUSTERED INDEX [IX_Messages_Workspace_Peer]
    ON [dbo].[Messages]([WorkspaceId] ASC, [PeerId] ASC);


GO
PRINT N'Creating Table [dbo].[Peers]...';


GO
CREATE TABLE [dbo].[Peers] (
    [Id]               BIGINT             IDENTITY (1, 1) NOT NULL,
    [WorkspaceId]      BIGINT             NOT NULL,
    [Name]             NVARCHAR (512)     COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL,
    [IsInternal]       BIT                NOT NULL,
    [Metadata]         JSON               NOT NULL,
    [InternalMetadata] JSON               NOT NULL,
    [Configuration]    JSON               NOT NULL,
    [CreatedAt]        DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_Peers] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_Peers_Workspace_Id] UNIQUE NONCLUSTERED ([WorkspaceId] ASC, [Id] ASC),
    CONSTRAINT [UQ_Peers_Workspace_Name] UNIQUE NONCLUSTERED ([WorkspaceId] ASC, [Name] ASC)
);


GO
PRINT N'Creating Index [dbo].[Peers].[IX_Peers_Workspace_CreatedAt]...';


GO
CREATE NONCLUSTERED INDEX [IX_Peers_Workspace_CreatedAt]
    ON [dbo].[Peers]([WorkspaceId] ASC, [CreatedAt] ASC);


GO
PRINT N'Creating Table [dbo].[PrincipalGrants]...';


GO
CREATE TABLE [dbo].[PrincipalGrants] (
    [Id]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [ObjectId]    NVARCHAR (64) COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL,
    [WorkspaceId] BIGINT        NULL,
    [Role]        NVARCHAR (32) NOT NULL,
    CONSTRAINT [PK_PrincipalGrants] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_PrincipalGrants_Object_Workspace_Role] UNIQUE NONCLUSTERED ([ObjectId] ASC, [WorkspaceId] ASC, [Role] ASC)
);


GO
PRINT N'Creating Index [dbo].[PrincipalGrants].[IX_PrincipalGrants_Workspace]...';


GO
CREATE NONCLUSTERED INDEX [IX_PrincipalGrants_Workspace]
    ON [dbo].[PrincipalGrants]([WorkspaceId] ASC);


GO
PRINT N'Creating Table [dbo].[SchemaVersion]...';


GO
CREATE TABLE [dbo].[SchemaVersion] (
    [Id]        TINYINT            NOT NULL,
    [Version]   INT                NOT NULL,
    [AppliedAt] DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_SchemaVersion] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[SessionPeers]...';


GO
CREATE TABLE [dbo].[SessionPeers] (
    [WorkspaceId]   BIGINT             NOT NULL,
    [SessionId]     BIGINT             NOT NULL,
    [PeerId]        BIGINT             NOT NULL,
    [Configuration] JSON               NOT NULL,
    [JoinedAt]      DATETIMEOFFSET (7) NOT NULL,
    [LeftAt]        DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_SessionPeers] PRIMARY KEY CLUSTERED ([WorkspaceId] ASC, [SessionId] ASC, [PeerId] ASC)
);


GO
PRINT N'Creating Index [dbo].[SessionPeers].[IX_SessionPeers_Workspace_Peer]...';


GO
CREATE NONCLUSTERED INDEX [IX_SessionPeers_Workspace_Peer]
    ON [dbo].[SessionPeers]([WorkspaceId] ASC, [PeerId] ASC);


GO
PRINT N'Creating Table [dbo].[Sessions]...';


GO
CREATE TABLE [dbo].[Sessions] (
    [Id]               BIGINT             IDENTITY (1, 1) NOT NULL,
    [WorkspaceId]      BIGINT             NOT NULL,
    [Name]             NVARCHAR (512)     COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL,
    [LifecycleState]   TINYINT            NOT NULL,
    [LifecycleVersion] INT                NOT NULL,
    [DeletionJobId]    BIGINT             NULL,
    [NextMessageSeq]   BIGINT             NOT NULL,
    [Metadata]         JSON               NOT NULL,
    [InternalMetadata] JSON               NOT NULL,
    [Configuration]    JSON               NOT NULL,
    [CreatedAt]        DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_Sessions] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_Sessions_Workspace_Id] UNIQUE NONCLUSTERED ([WorkspaceId] ASC, [Id] ASC),
    CONSTRAINT [UQ_Sessions_Workspace_Name] UNIQUE NONCLUSTERED ([WorkspaceId] ASC, [Name] ASC)
);


GO
PRINT N'Creating Index [dbo].[Sessions].[IX_Sessions_Workspace_State]...';


GO
CREATE NONCLUSTERED INDEX [IX_Sessions_Workspace_State]
    ON [dbo].[Sessions]([WorkspaceId] ASC, [LifecycleState] ASC);


GO
PRINT N'Creating Index [dbo].[Sessions].[IX_Sessions_Workspace_CreatedAt]...';


GO
CREATE NONCLUSTERED INDEX [IX_Sessions_Workspace_CreatedAt]
    ON [dbo].[Sessions]([WorkspaceId] ASC, [CreatedAt] ASC);


GO
PRINT N'Creating Table [dbo].[Workspaces]...';


GO
CREATE TABLE [dbo].[Workspaces] (
    [Id]               BIGINT             IDENTITY (1, 1) NOT NULL,
    [Name]             NVARCHAR (512)     COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL,
    [LifecycleState]   TINYINT            NOT NULL,
    [LifecycleVersion] INT                NOT NULL,
    [DeletionJobId]    BIGINT             NULL,
    [Metadata]         JSON               NOT NULL,
    [InternalMetadata] JSON               NOT NULL,
    [Configuration]    JSON               NOT NULL,
    [CreatedAt]        DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_Workspaces] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_Workspaces_Name] UNIQUE NONCLUSTERED ([Name] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_Messages_Metadata]...';


GO
ALTER TABLE [dbo].[Messages]
    ADD CONSTRAINT [DF_Messages_Metadata] DEFAULT '{}' FOR [Metadata];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Messages_InternalMetadata]...';


GO
ALTER TABLE [dbo].[Messages]
    ADD CONSTRAINT [DF_Messages_InternalMetadata] DEFAULT '{}' FOR [InternalMetadata];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Peers_Metadata]...';


GO
ALTER TABLE [dbo].[Peers]
    ADD CONSTRAINT [DF_Peers_Metadata] DEFAULT '{}' FOR [Metadata];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Peers_Configuration]...';


GO
ALTER TABLE [dbo].[Peers]
    ADD CONSTRAINT [DF_Peers_Configuration] DEFAULT '{}' FOR [Configuration];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Peers_InternalMetadata]...';


GO
ALTER TABLE [dbo].[Peers]
    ADD CONSTRAINT [DF_Peers_InternalMetadata] DEFAULT '{}' FOR [InternalMetadata];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Peers_IsInternal]...';


GO
ALTER TABLE [dbo].[Peers]
    ADD CONSTRAINT [DF_Peers_IsInternal] DEFAULT 0 FOR [IsInternal];


GO
PRINT N'Creating Default Constraint [dbo].[DF_SchemaVersion_AppliedAt]...';


GO
ALTER TABLE [dbo].[SchemaVersion]
    ADD CONSTRAINT [DF_SchemaVersion_AppliedAt] DEFAULT SYSDATETIMEOFFSET() FOR [AppliedAt];


GO
PRINT N'Creating Default Constraint [dbo].[DF_SessionPeers_Configuration]...';


GO
ALTER TABLE [dbo].[SessionPeers]
    ADD CONSTRAINT [DF_SessionPeers_Configuration] DEFAULT '{}' FOR [Configuration];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Sessions_InternalMetadata]...';


GO
ALTER TABLE [dbo].[Sessions]
    ADD CONSTRAINT [DF_Sessions_InternalMetadata] DEFAULT '{}' FOR [InternalMetadata];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Sessions_LifecycleVersion]...';


GO
ALTER TABLE [dbo].[Sessions]
    ADD CONSTRAINT [DF_Sessions_LifecycleVersion] DEFAULT 0 FOR [LifecycleVersion];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Sessions_NextMessageSeq]...';


GO
ALTER TABLE [dbo].[Sessions]
    ADD CONSTRAINT [DF_Sessions_NextMessageSeq] DEFAULT 1 FOR [NextMessageSeq];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Sessions_Metadata]...';


GO
ALTER TABLE [dbo].[Sessions]
    ADD CONSTRAINT [DF_Sessions_Metadata] DEFAULT '{}' FOR [Metadata];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Sessions_Configuration]...';


GO
ALTER TABLE [dbo].[Sessions]
    ADD CONSTRAINT [DF_Sessions_Configuration] DEFAULT '{}' FOR [Configuration];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Workspaces_Metadata]...';


GO
ALTER TABLE [dbo].[Workspaces]
    ADD CONSTRAINT [DF_Workspaces_Metadata] DEFAULT '{}' FOR [Metadata];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Workspaces_LifecycleVersion]...';


GO
ALTER TABLE [dbo].[Workspaces]
    ADD CONSTRAINT [DF_Workspaces_LifecycleVersion] DEFAULT 0 FOR [LifecycleVersion];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Workspaces_InternalMetadata]...';


GO
ALTER TABLE [dbo].[Workspaces]
    ADD CONSTRAINT [DF_Workspaces_InternalMetadata] DEFAULT '{}' FOR [InternalMetadata];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Workspaces_Configuration]...';


GO
ALTER TABLE [dbo].[Workspaces]
    ADD CONSTRAINT [DF_Workspaces_Configuration] DEFAULT '{}' FOR [Configuration];


GO
PRINT N'Creating Foreign Key [dbo].[FK_IdempotencyRecords_Workspaces]...';


GO
ALTER TABLE [dbo].[IdempotencyRecords] WITH NOCHECK
    ADD CONSTRAINT [FK_IdempotencyRecords_Workspaces] FOREIGN KEY ([WorkspaceId]) REFERENCES [dbo].[Workspaces] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Messages_Sessions]...';


GO
ALTER TABLE [dbo].[Messages] WITH NOCHECK
    ADD CONSTRAINT [FK_Messages_Sessions] FOREIGN KEY ([WorkspaceId], [SessionId]) REFERENCES [dbo].[Sessions] ([WorkspaceId], [Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Messages_Peers]...';


GO
ALTER TABLE [dbo].[Messages] WITH NOCHECK
    ADD CONSTRAINT [FK_Messages_Peers] FOREIGN KEY ([WorkspaceId], [PeerId]) REFERENCES [dbo].[Peers] ([WorkspaceId], [Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Peers_Workspaces]...';


GO
ALTER TABLE [dbo].[Peers] WITH NOCHECK
    ADD CONSTRAINT [FK_Peers_Workspaces] FOREIGN KEY ([WorkspaceId]) REFERENCES [dbo].[Workspaces] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_PrincipalGrants_Workspaces]...';


GO
ALTER TABLE [dbo].[PrincipalGrants] WITH NOCHECK
    ADD CONSTRAINT [FK_PrincipalGrants_Workspaces] FOREIGN KEY ([WorkspaceId]) REFERENCES [dbo].[Workspaces] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SessionPeers_Sessions]...';


GO
ALTER TABLE [dbo].[SessionPeers] WITH NOCHECK
    ADD CONSTRAINT [FK_SessionPeers_Sessions] FOREIGN KEY ([WorkspaceId], [SessionId]) REFERENCES [dbo].[Sessions] ([WorkspaceId], [Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SessionPeers_Peers]...';


GO
ALTER TABLE [dbo].[SessionPeers] WITH NOCHECK
    ADD CONSTRAINT [FK_SessionPeers_Peers] FOREIGN KEY ([WorkspaceId], [PeerId]) REFERENCES [dbo].[Peers] ([WorkspaceId], [Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Sessions_Workspaces]...';


GO
ALTER TABLE [dbo].[Sessions] WITH NOCHECK
    ADD CONSTRAINT [FK_Sessions_Workspaces] FOREIGN KEY ([WorkspaceId]) REFERENCES [dbo].[Workspaces] ([Id]);


GO
PRINT N'Creating Check Constraint [dbo].[CK_SchemaVersion_SingleRow]...';


GO
ALTER TABLE [dbo].[SchemaVersion] WITH NOCHECK
    ADD CONSTRAINT [CK_SchemaVersion_SingleRow] CHECK ([Id] = 1);


GO
PRINT N'Creating Check Constraint [dbo].[CK_Sessions_LifecycleState]...';


GO
ALTER TABLE [dbo].[Sessions] WITH NOCHECK
    ADD CONSTRAINT [CK_Sessions_LifecycleState] CHECK (([LifecycleState]=(2) OR [LifecycleState]=(1) OR [LifecycleState]=(0)));


GO
PRINT N'Creating Check Constraint [dbo].[CK_Workspaces_LifecycleState]...';


GO
ALTER TABLE [dbo].[Workspaces] WITH NOCHECK
    ADD CONSTRAINT [CK_Workspaces_LifecycleState] CHECK (([LifecycleState]=(2) OR [LifecycleState]=(1) OR [LifecycleState]=(0)));


GO
/*
Post-deployment script: stamps the single SchemaVersion row.
Idempotent: safe to run on every deploy. Monotonic: the stamp only ever moves forward, so running an older
script against a newer database cannot make it look older (SchemaDeployer refuses to deploy over one anyway).

The version literal below must equal SchemaInfo.CurrentVersion in
Nachos.DataLayer.SqlServer (asserted by SchemaDeployerTests.PostDeployVersion_MatchesSchemaInfo).
*/
MERGE [dbo].[SchemaVersion] AS target
USING (SELECT CAST(1 AS TINYINT) AS [Id], 1 AS [Version]) AS source -- SCHEMA VERSION LITERAL: keep in sync with SchemaInfo.CurrentVersion
ON target.[Id] = source.[Id]
WHEN MATCHED AND target.[Version] < source.[Version] THEN
    UPDATE SET [Version] = source.[Version], [AppliedAt] = SYSUTCDATETIME()
WHEN NOT MATCHED THEN
    INSERT ([Id], [Version], [AppliedAt]) VALUES (source.[Id], source.[Version], SYSUTCDATETIME());
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[IdempotencyRecords] WITH CHECK CHECK CONSTRAINT [FK_IdempotencyRecords_Workspaces];

ALTER TABLE [dbo].[Messages] WITH CHECK CHECK CONSTRAINT [FK_Messages_Sessions];

ALTER TABLE [dbo].[Messages] WITH CHECK CHECK CONSTRAINT [FK_Messages_Peers];

ALTER TABLE [dbo].[Peers] WITH CHECK CHECK CONSTRAINT [FK_Peers_Workspaces];

ALTER TABLE [dbo].[PrincipalGrants] WITH CHECK CHECK CONSTRAINT [FK_PrincipalGrants_Workspaces];

ALTER TABLE [dbo].[SessionPeers] WITH CHECK CHECK CONSTRAINT [FK_SessionPeers_Sessions];

ALTER TABLE [dbo].[SessionPeers] WITH CHECK CHECK CONSTRAINT [FK_SessionPeers_Peers];

ALTER TABLE [dbo].[Sessions] WITH CHECK CHECK CONSTRAINT [FK_Sessions_Workspaces];

ALTER TABLE [dbo].[SchemaVersion] WITH CHECK CHECK CONSTRAINT [CK_SchemaVersion_SingleRow];

ALTER TABLE [dbo].[Sessions] WITH CHECK CHECK CONSTRAINT [CK_Sessions_LifecycleState];

ALTER TABLE [dbo].[Workspaces] WITH CHECK CHECK CONSTRAINT [CK_Workspaces_LifecycleState];


GO
PRINT N'Update complete.';


GO
