/*
Deployment script for nachos_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "nachos_db"
:setvar DefaultFilePrefix "nachos_db"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering Table [dbo].[SchemaVersion]...';


GO
ALTER TABLE [dbo].[SchemaVersion]
    ADD [AppliedAt] DATETIMEOFFSET (7) CONSTRAINT [DF_SchemaVersion_AppliedAt] DEFAULT SYSDATETIMEOFFSET() NOT NULL;


GO
/*
Post-deployment script: stamps the single SchemaVersion row.
Idempotent: safe to run on every deploy. Monotonic: the stamp only ever moves forward, so running an older
script against a newer database cannot make it look older (SchemaDeployer refuses to deploy over one anyway).

The version literal below must equal SchemaInfo.CurrentVersion in
Nachos.DataLayer.SqlServer (asserted by SchemaDeployerTests.PostDeployVersion_MatchesSchemaInfo).
*/
MERGE [dbo].[SchemaVersion] AS target
USING (SELECT CAST(1 AS TINYINT) AS [Id], 1 AS [Version]) AS source -- SCHEMA VERSION LITERAL: keep in sync with SchemaInfo.CurrentVersion
ON target.[Id] = source.[Id]
WHEN MATCHED AND target.[Version] < source.[Version] THEN
    UPDATE SET [Version] = source.[Version], [AppliedAt] = SYSUTCDATETIME()
WHEN NOT MATCHED THEN
    INSERT ([Id], [Version], [AppliedAt]) VALUES (source.[Id], source.[Version], SYSUTCDATETIME());
GO

GO
PRINT N'Update complete.';


GO
